language: scala
scala:
  - 2.10.5
  - 2.11.7
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
script: travis_retry sbt clean coverage test
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  slack: krrrr38:TYeSnczrquLKpGVf6o6JAm8e
